# Source: minio-operator/templates/console-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "console"
  namespace: kuberhealthy
  labels:
    helm.sh/chart: minio-operator-4.0.11
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/version: "v4.0.11"
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'minio-operator'
spec:
  ports:
    - name: http
      port: 9090
    - name: https
      port: 9443
  selector:
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator-console
