# Source: minio-operator/templates/console-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator-console
  namespace: kuberhealthy
  labels:
    helm.sh/chart: minio-operator-4.0.11
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/version: "v4.0.11"
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'minio-operator'
    wave.pusher.com/update-on-config-change: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-operator
      app.kubernetes.io/instance: minio-operator-console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-operator
        app.kubernetes.io/instance: minio-operator-console
    spec:
      serviceAccountName: console-sa
      containers:
        - name: minio-operator
          image: "minio/console:v0.6.8"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9443
              name: https
          args:
            - server
          env:
            - name: CONSOLE_OPERATOR_MODE
              value: "on"
          resources: {}
