# Source: minio-operator/templates/console-ui.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-sa
  namespace: minio
  annotations:
    meta.helm.sh/release-name: 'minio-operator'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
